install 
#git
#keras
#pandas



nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
apt-get update
#apt-get upgrade
apt-get install python3-pip
apt-get install vim
pip3 install tensorflow-gpu
pip3 install django
pip3 install jupyter
pip3 install beautifulsoup4
pip3 install tqdm
pip3 install nltk
pip3 install pandas
pip3 install requests
pip3 install sklearn
pip3 install gensim
flair
-------------------------
apt-get install git
pip3 install git+https://github.com/boudinfl/pke.git 

python3 -m nltk.downloader stopwords
python3 -m nltk.downloader universal_tagset
python3 -m spacy download en # download the english model

git clone https://github.com/NVIDIA/apex
cd apex
pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

pip3 install spacy #test

pip3 install stanfordnlp
stanfordnlp.download('en')
-----------------------
apt-get update
apt-get install python3-tk